### ISSUE TITLE
Add Alert component

### ISSUE THREAD

**Issue by pedronauck** [FuelLabs/design-system#9]
## Tasks

- [x] `Alert` component
- [x] `Alert.Title` component
- [x] `Alert.Description` component
- [x] `Alert.Actions` component
- [x] `Alert.Button` component
- [x] Tests scenarios

## Usage

```jsx
import { Alert } from '@fuel-js/react';

/**
 * Basic example
 */
export default () => (
  <Alert status='error'>
    <Alert.Title>Your browser is outdated!</AlertTitle>
    <Alert.Description>Your experience may be degraded.</AlertDescription>
    <Alert.Actions>
      <Alert.Button>Dismiss</Alert.Button>
    </Alert.Actions>
  </Alert>
);
```

## Custom props

- `status: 'error' | 'success' | 'warning' | 'info'`
- `variant:  'subtle' | 'solid' | 'left-accent' | 'top-accent'

## References

- Heavilly inspired on [Chakra's Alert](https://chakra-ui.com/docs/components/feedback/alert)
<img width="789" alt="Screen Shot 2022-05-02 at 12 31 09" src="https://user-images.githubusercontent.com/2029172/166261810-7839db97-a616-4c8c-9923-5305bd57344d.png">

## Tests Scenarios

- [x] a11y

**Comment by pedronauck** [comment]
closed on commit 57bbb1c767e6c6ad84ba4ba30d223a61b2ad3c61
